spring.application.name=loginserver-real

# Auth 서버 URL (인증 및 JWT 발급)
auth.server.url=http://authserver:8080/api/auth/login

# Auth 서버 회원가입 URL (DB 사용자 등록)
auth.server.register.url=http://authserver:8080/api/auth/register

# Ingress를 통한 Order 서비스 URL
ingress.url=http://ingress-nginx-controller.ingress-nginx.svc.cluster.local

